# Generated by Django 5.1.4 on 2026-08-29 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tried', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('was_successful', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin login attempt',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('program', models.CharField(blank=True, max_length=200)),
                ('period', models.CharField(blank=True, help_text="e.g. '2025 – Present'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (most recent first).')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Maryam Bukar', max_length=150)),
                ('headline', models.CharField(default='Aspiring Data Scientist & Analyst / Software Developer', help_text='Short line under the name on the homepage hero.', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short paragraph shown in the hero section.')),
                ('university', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site owner profile',
                'verbose_name_plural': 'Site owner profile',
            },
        ),
        migrations.CreateModel(
            name='AcademicFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_program', models.CharField(blank=True, max_length=200)),
                ('class_standing', models.CharField(blank=True, help_text="e.g. 'University Student'", max_length=100)),
                ('cgpa', models.CharField(blank=True, help_text="e.g. '3.52 / 4.00'", max_length=20)),
                ('deans_list', models.BooleanField(default=False)),
                ('deans_list_detail', models.CharField(blank=True, help_text="e.g. 'Consecutive semesters'", max_length=200)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_facts', to='core.siteowner')),
            ],
            options={
                'verbose_name': 'Academic facts',
                'verbose_name_plural': 'Academic facts',
            },
        ),
    ]
